### ISSUE TITLE
Questions and Issues with Meteorology Dataset and Exogenous/Endogenous Variables

### ISSUE THREAD

**Issue by gsoykan** [thuml/TimeXer#1]
Dear authors,

Thank you for providing this insightful paper. I have a few concerns and questions regarding the repository:

1. I downloaded the **meteorology dataset**, and I noticed that the scripts include both `wind.sh` and `temp.sh`. While the uploaded dataset contains `temp.npy`, it seems to be missing `wind.npy`. Could you kindly add the `wind.npy` file to the public dataset, if possible?

2. In the **meteorology dataset**, could you explain the purpose of the `era5_norm.npy` data? It would be helpful to understand how it is used within the context of the model.

3. For the implementation, it might be beneficial to add a section to the README that explains how exogenous and endogenous variables are processed. Additionally, if someone wants to create their own custom dataset for this method, how should they proceed? Currently, the only difference appears to be the features `MS` or `M`, so is it possible to use the `M` setting with this approach (exo - endo)?

Thank you for your time and assistance!

Best regards,  
Gürkan Soykan

**Comment by wang-lucy** [comment]
1. We have already included wind.npy in the uploaded dataset. Could I ask you to kindly check it again?
2. The meteorology dataset consists of endogenous series in `wind.npy` / `temp.npy` derived from National Centers for Environmental Information, and corresponding exogenous series in `era5_norm.npy` obtained from ERA5. The ERA5  is a global climate reanalysis dataset containing meteorological indicators, we take them as external information to enhance the temperature prediction of 3,850 stations worldwide, please refer to Figure 4 in the main text.
3. Thanks for your suggestions. We are using the MS setup introduced by Informer, i.e. multivariate prediction univariate. In this configuration, the last column of the dataset is labelled as `OT`, representing the endogenous variable to be predicted, while all other variables are treated as exogenous. The `M` setting indicates a canonical multivariate forecasting task, which is also supported by TimeXer.

**Comment by gsoykan** [comment]
Thank you for your response and detailed explanations.

Could you kindly elaborate further on point 3, particularly regarding whether this scenario is feasible?

For instance, in the meteorology dataset with 20 + 1 (OT) features, if I disregard OT and choose 3 variables as endogenous while treating the remaining 17 as exogenous, would this be a valid setup? What adjustments would be necessary to create a scenario like this, which could be considered a limited “M” setting with an arbitrary distribution of exogenous and endogenous features?

Thank you in advance for your assistance.

**Comment by amw5g** [comment]
I'd like to add my interest in also seeing a more concrete example of the meteorology forecasting work.
