### ISSUE TITLE
如何复现论文中协变量缺失情况下的预测效果？

### ISSUE THREAD

**Issue by liujian123223** [thuml/TimeXer#16]
您好，我对你们的工作很感兴趣。我在使用TimeXer进行实验时，想验证论文中在协变量缺失情况下的预测效果。因此我将我的数据集的协变量部分按照不同比例设置缺失值，并用论文同样的方式使用0来代替缺失的部分。但我发现随着协变量比例的升高（目标变量完整不变）我的预测结果反而整体更好了。当我将所有的协变量全部设置为0的时候效果达到最好。你能指出我的错误在哪吗？我需要如何正确的设置才能完成这个实验？

**Comment by liujian123223** [comment]
我是对我的训练数据csv文件，先设置0来代替缺失值，然后输入到你们的代码中读取csv文件并进行训练

**Comment by wang-lucy** [comment]
您好，这个可能是和您协变量的选择有关的，事实上并不是所有外部变量的引入都是对模型有益的，文中所选择的EPF数据集中的协变量是已经经过相关领域的研究验证对预测有帮助的变量。

**Comment by liujian123223** [comment]
但我使用光伏数据集，太阳辐射照度是协变量，它对光伏发电量的预测是有很明显的积极作用的，但我还是遇到了这个问题。

**Comment by wang-lucy** [comment]
建议您检查一下patch大小和模型参数设置是否适合您的新任务
