### ISSUE TITLE
模型实验的问题。

### ISSUE THREAD

**Issue by bigdata0** [thuml/TimeXer#2]
您好，将您的工作复现后我发现，用外生变量和内生变量去预测单变量，精度显著低于先进行多变量的训练然后输出目标变量"OT"的预测结果，只需要将validate和test函数中的dim改为-1，训练中的函数损失使用多维损失，这样训练出的模型精度远高于论文中所述的单变量预测结果。请问这样的差距下，为何要使用协变量和内生变量预测目标变量，而不是使用协变量和内生变量进行多维预测然后输出目标变量的预测结果？

**Comment by wang-lucy** [comment]
您好，使用TimeXer进行多变量训练理论上是进行多个单变量+协变量预测，因此使用多维预测训练的数据量增大可能会导致效果的提升，本文采用的是TSLib中标准的训练-测试流程。
