### ISSUE TITLE
关于多元变量预测验证问题

### ISSUE THREAD

**Issue by RJDN1** [thuml/TimeXer#3]
作者大大你好，在多元变量预测模型中，我经常遇到OT单变量进行预测的效果比OT单变量+多个协变量的效果要好。

我曾在crossformer模型里试验过OT变量单变量预测、OT变量+5协变量预测、OT变量+10协变量预测。最后发现整体预测效果都好于informer，但是横向比较单变量预测效果最好。

注意到作者只以目标变量作为预测的目的协变量只是辅助。在这种应用情景里，如果只输入单变量的预测效果高于多变量，是不是说明预测精度的提升只是模型的精进而可能并没有学到变量之间的关系。

请问作者大大，有在这个模型做过相应的验证吗？或者有必要做这种验证吗？ @wuhaixu2016

**Comment by wang-lucy** [comment]
这个实验结果是与数据集有非常大关系的，现有的多变量数据集中多变量间的相关关系是十分复杂的，并不是所有变量关系都会对预测带来正向帮助也有可能会引入噪音。
在协变量EPF数据集中，引入的两个协变量是已经被验证对目标变量预测有益的变量，我们在正文表5的消融实验中也验证了将协变量置零后模型效果会下降。
