### ISSUE TITLE
Discrepancies in Reproduced Multivariate Forecasting Results

### ISSUE THREAD

**Issue by mosszhd** [thuml/TimeXer#4]
First of all, thank you for providing the code.

I am attempting to reproduce the multivariate forecasting results from the paper. For most prediction lengths, the results align with the paper; however, for ETTh1 and ETTh2 at a prediction length of 720, I am observing discrepancies in the MSE and MAE values.

For ETTh1 with a prediction length of 720, my results show an MSE of 0.503 and an MAE of 0.494, compared to the reported 0.469 and 0.461 in the paper. Similarly, for ETTh2 at a prediction length of 720, my MSE is 0.449 and MAE is 0.453, while the paper reports 0.408 and 0.432, respectively.

Could you confirm if the provided bash script contains the exact hyperparameter settings used in the paper for reproducing these multivariate forecasting results, or if any additional adjustments are required? Thank you!

**Comment by wang-lucy** [comment]
Hello, we have repeated the multivariate experiment of ETTh1 and ETTh2 and the results are consistent with the paper.
<img width="1439" alt="截屏2024-11-04 10 31 08" src="https://github.com/user-attachments/assets/f8ee9d99-4ef0-4977-b0c6-d00f406a6172">
<img width="1439" alt="截屏2024-11-04 10 31 19" src="https://github.com/user-attachments/assets/f14abfa4-2141-4727-a78a-b78429232fa1">
We kindly ask you to confirm your experimental environment (including torch version and GPU) is consistent with the requirements we provide.

**Comment by mosszhd** [comment]
Thanks so much for the help! Earlier, I was training on a RTX 3060 with the same setup and environment you provided, and I was getting the results as I’d mentioned before. But after switching to a RTX 4090, as mentioned in the paper, I got the similar results you reported. It looks like training the same model on different GPUs can lead to slight variations in results.

Thanks again for your help!

**Comment by wiwi** [comment]
Very sensitive to the training environment, does this mean that the model does not generalize well?

**Comment by a1473838623** [comment]
> Very sensitive to the training environment, does this mean that the model does not generalize well?

Agree.
