### ISSUE TITLE
Some of the EPF data (BE.csv and FR.csv) are nearly identical

### ISSUE THREAD

**Issue by junhyeokkang** [thuml/TimeXer#5]
Thank you for sharing your valuable research results and code.

I am currently reviewing the EPF dataset, and I've noticed that the two datasets, BE.csv and FR.csv, are nearly identical. 

Could you please provide a source where I might be able to obtain the original data? 

Thank you very much!

**Comment by wang-lucy** [comment]
Hi, the EPF dataset is obtained from [nbeatsx](https://github.com/cchallu/nbeatsx) repository.
