### ISSUE TITLE
关于推理阶段的外协变量与目标变量长度不一致的问题

### ISSUE THREAD

**Issue by lk1983823** [thuml/TimeXer#9]
在训练阶段，代码中给出的样例是历史数据长度96，预测数据长度24。在推理阶段，如果我拥有历史数据长度也是96，但是还有预测期的外协变量，其长度是24。那么，如何输入模型，实现预测？ 因为这个时候，输入变量中，目标变量的长度是96，但是外协变量的长度是96+24=120. 谢谢。

**Comment by wang-lucy** [comment]
可以考虑设置外生变量的长度为120，在训练阶段对数据进行zero padding到120。
